### ISSUE TITLE
 "in_reply_to_user_id" is coming as  float, but should be a string.

### ISSUE THREAD

**Issue by patrick-lee-warren** [dhudsmith/pull_twitter#19]
The other ids seem to be correctly specified as str, but this one is coming in with a decimal.

**Comment by dhudsmith** [comment]
Carl's theory is that the missing values are causing the pandas series to be coerced to float.

**Comment by NickDeas** [comment]
It may also be that the integers are too large, so when pandas attempts to infer the datatype of id columns, it places them in scientific notation (inserting a decimal) and coerces them to floats rather than integers.  If the csvs are read through pandas as well, these are interpretted as floats.

**Comment by patrick-lee-warren** [comment]
We aren't ever going to be any mathematical operations on any of these ids. There is no reason to treat the as anything but strings, ever.

**Comment by NickDeas** [comment]
This has now been resolved in Pull Request #22.  The float data-typed id columns specified above have been converted to remove the decimal and can now be interpreted as strings correctly.
